main = './worker.ts'
compatibility_date = "2024-10-18"

[env.staging]
name = "eigen-web-association-test-worker"
workers_dev = true # Deploy to the workers.dev subdomain

[env.production]
name = "eigen-web-association-worker"